version: "3.7"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: sh -c "
      python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=local_password
    depends_on:
      - db

  db:
    image: postgres:12.5-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=local_password
